-- COMBINE ALL TABLES INTO ONE RAW MASTER TABLE AND VALIDATE THE ROW COUNT

-- Combine all monthly tables into one raw master table
CREATE TABLE cyclistic_trips_raw AS
SELECT * FROM mar_2025
UNION ALL
SELECT * FROM apr_2025
UNION ALL
SELECT * FROM may_2025
UNION ALL
SELECT * FROM jun_2025
UNION ALL
SELECT * FROM jul_2025
UNION ALL
SELECT * FROM aug_2025
UNION ALL
SELECT * FROM sept_2025
UNION ALL
SELECT * FROM oct_2025
UNION ALL
SELECT * FROM nov_2025
UNION ALL
SELECT * FROM dec_2025
UNION ALL
SELECT * FROM jan_2026
UNION ALL
SELECT * FROM feb_2026;

-- Validate and check the row count
SELECT COUNT(*) AS total_rows
FROM cyclistic_trips_raw;